---
title: "STA210 - Homework #10"
author: "Parker Williams"
date: "2023-11-19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Sorting
```{r}
library(Lahman)
data("Teams")
```

## (a) LAN & ANA
```{r}
library(dplyr)
condition = Teams$teamID %in% c("ANA", "LAN")
df = Teams[condition, ]

df = subset(Teams, subset = condition)
df = Teams %>% filter(condition)
```

## (b) sort or arrange values in decreasing order

-sort() = 1D
-order() = 2D

```{r}
sort(df$teamID, decreasing=T)
```
ANA initially displays on the 66th row

## (c)
```{r}
condition = order(df$W, decreasing = T)
df.ordered = df[condition, ]


condition1 = df$teamID == "LAN"
condition2 = df$teamID == "ANA"

LAN_ordered = df.ordered[condition1, ]
ANA_ordered = df.ordered[condition2, ]
```

LAN best season = 111 wins (2022)
ANA best season = 86 wins (2001)

# 2. Reshaping 

## (a) Suppose we have the following data frame in R that is currently in a long format:
```{r}
#create data frame
play <- data.frame(player = rep(c('A', 'B'), each=4),
                   year=rep(c(1, 1, 2, 2), times=2),
                   stat=rep(c('points', 'assists'), times=4),
                   amount=c(14, 6, 18, 7, 22, 9, 38, 4))
# view data
head(play)

# wide data
library(tidyr)

play_wide <- play %>% 
  pivot_wider(names_from = stat, values_from = amount)
```

## (b) Wide to long
```{r}
#create data frame
df <- data.frame(player=c('A', 'B', 'C', 'D'),
year1=c(12, 15, 19, 19),
year2=c(22, 29, 18, 12))

df_long <- df %>% 
  pivot_longer(cols = starts_with("year"), 
               names_to = "variable",
               values_to = "Points")
```

## (c) Long to Wide
```{r}
data("Pitching")

Pitchers = Pitching %>% 
  filter(teamID == c("LAN", "ANA")) %>% 
  select(playerID, yearID, teamID, W)

Pitchers = Pitchers %>% filter(yearID >= 2000)

Pitchers_wide <- Pitchers %>%
  pivot_wider(names_from = teamID, values_from = W)
```

## (d) Wide to Long
```{r}
Pitchers_long <- Pitchers_wide %>%
  pivot_longer(cols = c(LAN, ANA), names_to = "Teams", values_to = "Wins", values_drop_na = TRUE)
```








